ApplicationDetails/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "ApplicationDetails"

urlpatterns = [
    path('', login_required(views.ApplicationListView.as_view()), name='application_list'),
    path('applications/<date>/', login_required(views.ApplicationDetailListView.as_view()), name='application_detail_list'),
    path('applications/<date>/<int:application_id>/', login_required(views.ApplicationDetailView.as_view()), name='application_details'),
    path('add_application_details/', login_required(views.ApplicationCreateView.as_view()), name='add_job_application'),
    path('applications/<int:application_id>/update/', login_required(views.ApplicationUpdateView.as_view()), name='edit_application'),
    path('applications/<int:application_id>/delete/', login_required(views.ApplicationDeleteView.as_view()), name='delete_application'),
]

JobPortalApplicationTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as view_form
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('ApplicationDetails.urls')),
    path("", include('users.urls')),
    path("register/", view_form.register, name='register'),
    path("profile/", view_form.profilepage, name="profile"),
    path("login/", authentication_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", authentication_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('admin/', admin.site.urls),
    path('new_password/', authentication_views.PasswordChangeView.as_view(template_name="users/new_password.html"), name='new_password'),
    path('new_password/set/', authentication_views.PasswordChangeDoneView.as_view(template_name="users/new_password_set.html"), name="password_change_done"),
    path('password_reset/', authentication_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name='password_reset'),
    path('password_reset/email/', authentication_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', authentication_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/done/', authentication_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profilepage, name="profile"),
    path("update_profile", views.profile_details, name="profile_details"),
]

ApplicationDetails/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
# Create your models here.

class JobApplication(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1,)
    date = models.DateField(verbose_name="Applied Date")
    portal_name = models.CharField(max_length=100, verbose_name="Portal's Name")
    job_title = models.CharField(max_length=200, verbose_name="Job Title")
    company_name = models.CharField(max_length=200, verbose_name="Company Name")
    job_location = models.CharField(max_length=300, blank=True, verbose_name="Job Location")
    contact_details = models.TextField(blank=True, verbose_name="Company Contact Details")
    application_link = models.URLField(verbose_name="Link to Job Application")
    remarks = models.TextField(verbose_name="Remarks")
    
    def get_absolute_url(self):
        return reverse("ApplicationDetails:application_details", kwargs={"application_id": self.id})

    def __str__(self):
        return f"{self.job_title} at {self.company_name}"

ApplicationDetails/forms.py
from django import forms
from .models import JobApplication

class JobApplicationForm(forms.Form):
    class Meta:
        model = JobApplication
        fields = ['date', 'portal_name', 'job_title', 'company_name', 'contact_details', 'application_link', 'remarks']

ApplicationDetails/views.py
from django.shortcuts import render, redirect
from .models import JobApplication
from .forms import JobApplicationForm
from django.db import models
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from datetime import date
from django.urls import reverse_lazy, reverse
from django.db.models import Q
# Create your views here.

class ApplicationListView(ListView):
    model = JobApplication
    context_object_name = 'application_counts'
    template_name = 'ApplicationDetails/application_list.html'
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        return super().get_queryset().filter(user=user).values('date').annotate(count=models.Count('id')).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context['application_counts']:  # Check if any data exists
            context['no_data'] = True  # Add a flag for no data
        return context


class ApplicationDetailListView(ListView):
    model = JobApplication
    context_object_name = 'applications'
    template_name = 'ApplicationDetails/application_detail_list.html'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        date_str = self.kwargs.get('date')
        search_field = self.request.GET.get('search_field')

        if date_str:
            try:
                selected_date = date.fromisoformat(date_str)
                queryset = self.model.objects.filter(date=selected_date)
            except ValueError:
                queryset = self.model.objects.none()
        else:
            queryset = self.model.objects.all()

        if user.is_authenticated:
            queryset = queryset.filter(user=user)

        if search_field:
            # Search across multiple fields using Q objects
            queryset = queryset.filter(
                Q(company_name__icontains=search_field) | Q(job_title__icontains=search_field) | Q(portal_name__icontains=search_field) | Q(job_location__icontains=search_field)
            )

        return queryset.order_by('-id')

class ApplicationCreateView(CreateView):
    model = JobApplication
    fields = ['date', 'portal_name', 'job_title', 'company_name', 'job_location', 'contact_details', 'application_link', 'remarks']
    template_name = 'ApplicationDetails/add_job_application.html'
    
    def get_success_url(self):
        updated_object = self.object
        return reverse_lazy('ApplicationDetails:application_details', kwargs={'date': updated_object.date, 'application_id': updated_object.id})
    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ApplicationDetailView(DetailView):
    model = JobApplication
    template_name = 'ApplicationDetails/application_details.html'
    pk_url_kwarg = 'application_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add any additional context data specific to the application detail
        return context

    def get_queryset(self):
        user = self.request.user
        date_str = self.kwargs.get('date')
        if date_str:
            try:
                selected_date = date.fromisoformat(date_str)
                queryset = self.model.objects.filter(date=selected_date)
            except ValueError:
                queryset = self.model.objects.none()
        else:
            queryset = self.model.objects.all()

        if user.is_authenticated:
            queryset = queryset.filter(user=user)
        return queryset

class ApplicationUpdateView(UpdateView):
    model = JobApplication
    fields = ['date', 'portal_name', 'company_name', 'job_location', 'contact_details', 'application_link', 'remarks']
    template_name = 'ApplicationDetails/edit_application.html'
    pk_url_kwarg = 'application_id'

    def get_success_url(self):
        return reverse_lazy('ApplicationDetails:application_details', kwargs={'date': self.object.date, 'application_id': self.object.pk})

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['jobapplication'] = self.object
        return context

class ApplicationDeleteView(DeleteView):
    model = JobApplication
    template_name = 'ApplicationDetails/delete_application.html'
    pk_url_kwarg = 'application_id'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)
    
    def get_success_url(self):
        return reverse_lazy('ApplicationDetails:application_detail_list', kwargs={'date': self.object.date})

ApplicationDetails/templates/ApplicationDetails/add_job_application.html
{% extends 'ApplicationDetails/base.html' %}

{% block body %}
<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid justify-content-center">
        <div class="row ">
            <div class="col-sm-8 col-md-6 col-lg-4 offset-md-4 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 450px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h5 class="mb-0">Add Application Details</h5>
                        </div>
                    </div>
                    <div class="card-body text-center px-4">
                        <form method="POST" class="form-group mb-3">
                            {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group mb-3">
                            {% if field.name == 'date' %}
                                {{ field.as_p }}
                                <input type="date" class="form-control form-control-date" id="{{ field.id_for_label }}" name="{{ field.name }}" placeholder="Enter Application Date"  {% if field.field.required %} required{% endif %}>
                            {% else %}
                                {{ field.as_p }}
                                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" placeholder="{{ field.label }}" {% if field.field.required %} required{% endif %}>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-outline-primary" type="submit">Save Application Details</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ApplicationDetails/templates/ApplicationDetails/application_detail_list.html
{% extends 'ApplicationDetails/base.html' %}
{% block body %}
<body style="background-image: url('{% static "ApplicationDetails/images/Application_job.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    {% include "search_detail_list.html" %}
    <div class="container-fluid justify-content-center">
        <div class="row ">
            <div class="col-sm-10 col-md-10 col-lg-10 offset-md-1 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 1080px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h1>Job Applications for {{ applications.0.date }}</h1>
                        </div>
                    </div>
                     <div class="card-body text-center px-4">
                        <div class="table-responsive table-responsive-md table-responsive-sm">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Portal's Name</th>
                                    <th scope="col">Job Title</th>
                                    <th scope="col">Company Name</th>
                                    <th scope="col">Job Location</th>
                                    <th scope="col">Details</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for application in applications %}
                                    <tr>
                                        <th scope="row"> {{ application.portal_name }} </th>
                                        <th scope="row"> {{ application.job_title }} </th>
                                        <th scope="row"> {{ application.company_name }} </th>
                                        <th scope="row">{{ application.job_location }}</th>
                                        <td><a href="{% url 'ApplicationDetails:application_details' application.date application.id %}"><button class="btn btn-outline-primary">View Details</button></a> </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>

{% include "pagination.html" with page=page_obj %}
</body>
{% endblock %}

ApplicationDetails/templates/ApplicationDetails/application_details.html
{% extends 'ApplicationDetails/base.html' %}
{% block body %}

<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid mt-5">
        <div class="col mt-5">
            <div class="row-md-6 lg-6">
                <h1 class="text-white" style="text-align:center"> {{ object.job_title }} </h1>
            </div>
            <div class="row-md-6">
                <h1 class="text-white" style="text-align:center"> {{ object.company_name }} </h1>
                <h2 class="text-white" style="text-align:center"> {{ object.job_location }} </h2>
                <h3 class="text-white" style="text-align:center"> {{ object.portal_name }} </h3>
                <h5 class="text-white" style="text-align:center"> {{ object.contact_details }} </h5>
                <h5 style="text-align:center"><a href="{{ object.application_link }}" class="link-light link-underline-info">Application Link</a></h5>
                <h6 class="text-white text-wrap text-center" style="text-align:center; word-wrap: break-word; overflow-wrap: break-word; white-space: pre-wrap; text-align: center; padding: 0 10px;"> {{ object.remarks }} </h6>
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 text-center">
            <a href="{% url 'ApplicationDetails:edit_application' object.id %}" class="btn btn-info">Edit Application Details</a>
            </div>
            <div class="col-md-6 text-center">
            <a href="{% url 'ApplicationDetails:delete_application' object.id %}" class="btn btn-danger">Delete Application Details</a>
            </div>
        </div>
    </div>
</body>
{% endblock %}

ApplicationDetails/templates/ApplicationDetails/application_list.html
{% extends 'ApplicationDetails/base.html' %}
{% block body %}
<body style="background-image: url('{% static "ApplicationDetails/images/Application_job.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col-sm-8 col-md-6 col-lg-6 offset-md-3 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 720px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h1>Job Applications</h1>
                        </div>
                    </div>
                    <div class="card-body text-center px-4">
                        <div class="table-responsive table-responsive-md table-responsive-sm">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Date</th>
                                    <th scope="col">Applications Count</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% if no_data %}
                                        <tr class="alert alert-warning" role="alert">
                                            <td colspan="2" class="text-warning text-center fs-6 fw-semibold">There are no Job Applications found.</td>
                                        </tr>
                                    {% else %}
                                        {% for application_count in application_counts %}
                                        <tr>
                                            <th scope="row">{{ application_count.date }}</th>
                                            <td><a href="{% url 'ApplicationDetails:application_detail_list' application_count.date %}">{{ application_count.count }}</a></td>
                                        </tr>
                                        {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "pagination.html" with page=page_obj %}
</body>
{% endblock %}

ApplicationDetails/templates/ApplicationDetails/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Job Portal Application Tracker</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/4129906e3e.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-success  bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'ApplicationDetails:application_list' %}">Job Portal Application Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="justify-content-end" id="navbarNav">
                <ul class="nav nav-tabs justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ApplicationDetails:add_job_application' %}">Add Today's Application Details</a>
                    </li>
                    <li class="nav-item">
                    <form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button class="nav-item nav-link" type="submit">Logout</button>
                    </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}"><i class="fa-solid fa-user"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-item nav-link" role="button" href="{% url 'login' %}">LogIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
                    </li>
                {% endif %}
                </ul>

            </div>
        </div>
    </nav>


    {% block body %}
    {% endblock %}
</body>
</html>

ApplicationDetails/templates/ApplicationDetails/delete_application.html
{% extends 'ApplicationDetails/base.html' %}
{% block body %}
<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
  <div class="container mt-5 border border-primary-subtle rounded-5 alert alert-danger" role="alert" >
      <div class="row justify-content-center mt-5 mb-4">
        <div class="col-md-8 mt-5 mb-4">
          <form method="POST">
              {% csrf_token %}
              <h2 class="fs-2 alert-heading lh-base fw-semibold text-center">Are you sure you want to <span class="text-danger bg-primary-subtle border border-primary-subtle rounded-2">delete</span> details of <span class="text-primary-emphasis">{{jobapplication.portal_name}}</span> application in <span class="text-success">{{jobapplication.company_name}}</span> as <span class="fs-2 fw-bold text-success-emphasis">{{jobapplication.job_title}}</span> </h2>
              <div class="text-center mt-3">
                  <a href="{% url 'ApplicationDetails:application_detail_list' object.date %}"> <button type="submit" class="btn btn-warning">Confirm</button> </a>
              </div>
          </form>
        </div>
      </div>
  </div>
</body>
{% endblock %}

ApplicationDetails/templates/ApplicationDetails/edit_application.html
{% extends 'ApplicationDetails/base.html' %}
{% block body %}
<body style="background-image: url('{% static "ApplicationDetails/images/Application_job.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid justify-content-center">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 offset-md-0 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 1080px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h5 class="mb-0">Edit Application for {{ jobapplication.job_title }} in {{ jobapplication.company_name }} </h5>
                        </div>
                    </div>
                    <div class="card-body px-4" style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
                        <form method="POST" class="row g-3 mb-3">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="col-md-5 mb-3 text-info">
                                <strong><label for="floatingInput">{{field.label_tag}}</label></strong>
                            </div>
                            <div class="col-md-7 mb-3">
                                {{ field }}

                            </div>
                            {% endfor %}
                            <div class="form-group text-center">
                                <a href="{% url 'ApplicationDetails:application_details' jobapplication.date jobapplication.id %}"> <button type="submit" class="btn btn-outline-primary"> Update Application </button> </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}